### ISSUE TITLE
Javascript not functioning as expected on Chrome

### ISSUE THREAD

**Issue by semioticrobotic** [sassoftware/sassoftware.github.io#1]
When loading the site with Chrome, sections with content pulled via from the GitHub API via Javascript do not render as expected. In particular, items are not sorted according to the proper logic(s).

On Firefox the lists look like this:

![Screenshot 2024-09-20 at 15 54 39](https://github.com/user-attachments/assets/bf15eac6-ab4c-4e3c-9c25-084721c81121)

On Chrome the lists look like this:

![Screenshot 2024-09-20 at 15 51 54](https://github.com/user-attachments/assets/70c72e2a-a031-4258-a0b3-a331ca4cb744)

For sake of comparison, on Safari the lists look like this:

![Screenshot 2024-09-20 at 15 53 13](https://github.com/user-attachments/assets/a84160be-c657-47f4-9a62-55f74046a616)

**Comment by semioticrobotic** [comment]
Asked @isharacomix for some help here.

**Comment by isharacomix** [comment]
Fixed in d14572cd4373e737f518c2ab3abad3f28e294c33 - the compareFn is supposed to return 1 or -1, and I was using True and False.
